import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFAE2F34),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFF6B6B),
    onPrimaryContainer: Color(0xFF6D0010),
    secondary: Color(0xFF006A65),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFF79F3EA),
    onSecondaryContainer: Color(0xFF006F69),
    tertiary: Color(0xFF6D5E00),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFC1AB38),
    onTertiaryContainer: Color(0xFF4A3F00),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF93000A),
    surface: Color(0xFFFBF9F8),
    onSurface: Color(0xFF1B1C1C),
    surfaceContainerHighest: Color(0xFFE4E2E1),
    onSurfaceVariant: Color(0xFF584140),
    outline: Color(0xFF8C706F),
    outlineVariant: Color(0xFFE0BFBD),
    inverseSurface: Color(0xFF303030),
    onInverseSurface: Color(0xFFF3F0F0),
    inversePrimary: Color(0xFFFFB3B0),
    surfaceTint: Color(0xFFAE2F34),
  );

  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFB4AB),
    onPrimary: Color(0xFF690014),
    primaryContainer: Color(0xFF8C1520),
    onPrimaryContainer: Color(0xFFFFDAD8),
    secondary: Color(0xFF4CDAD0),
    onSecondary: Color(0xFF003734),
    secondaryContainer: Color(0xFF00504C),
    onSecondaryContainer: Color(0xFF79F3EA),
    tertiary: Color(0xFFE4C64F),
    onTertiary: Color(0xFF393000),
    tertiaryContainer: Color(0xFF534600),
    onTertiaryContainer: Color(0xFFFBE36A),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF1A1110),
    onSurface: Color(0xFFF0DEDC),
    surfaceContainerHighest: Color(0xFF584140),
    onSurfaceVariant: Color(0xFFE0BFBD),
    outline: Color(0xFFA58988),
    outlineVariant: Color(0xFF584140),
    inverseSurface: Color(0xFFF0DEDC),
    onInverseSurface: Color(0xFF352B2A),
    inversePrimary: Color(0xFFAE2F34),
    surfaceTint: Color(0xFFFFB4AB),
  );
}